name: Terraform CI/CD

on:
  pull_request:
    paths:
      - "terraform/**"
      - "src/lambda/code_watcher/**"
      - ".github/workflows/terraform.yml"
  push:
    branches: [ "main" ]
    paths:
      - "terraform/**"
      - "src/lambda/code_watcher/**"
      - ".github/workflows/terraform.yml"

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    env:
      TF_IN_AUTOMATION: "true"
      AWS_REGION: "us-east-1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      # Configure AWS creds via OIDC (recommended). Create an IAM role trust for your GitHub org/repo.
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        working-directory: terraform
        run: terraform plan -var-file="envs/dev.tfvars"

      - name: Terraform Apply (main)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        working-directory: terraform
        run: terraform apply -auto-approve -var-file="envs/dev.tfvars"
